plugins {
    id 'java'
    id 'war'
}

group = 'com.zavabank'
version = '1.0.0'

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'javax.servlet:javax.servlet-api:4.0.1'
    implementation 'org.apache.struts:struts2-core:2.5.30'
    implementation 'com.microsoft.sqlserver:mssql-jdbc:12.8.1.jre11'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

war {
    archiveBaseName = 'ROOT'
}
